---
- name: "Set timezone to {{ basic_timezone }}"
  timezone:
    name: "{{ basic_timezone }}"

- name: Ensure ntp is installed
  apt:
    name: ntp
    state: present

- name: Set ntp configuration files
  template:
    src: 'ntp.conf.j2'
    dest: '/etc/ntp.conf'
    owner: root
    group: root
    mode: 0644
  notify: Restart ntp
