---

- name: Install zabbix-agent
  apt:
    name: [ 'zabbix-agent' ]
    state: present

- name: Ensure zabbix-agent.config file is present
  template:
    src: 'templates/zabbix_agentd.conf.j2'
    dest: '/etc/zabbix/zabbix_agentd.conf'
  notify:
    - Restart zabbix agent
